config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container mt-3">
  <h1>All our Flats(<%= @flats.count %>)</h1>
  <p>You searched for . We found 4 flats out of our 4 on our website.</p>
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="card m-3" style="width: 18rem;">
      <img src="https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200" alt="" class="card-img-top">
      <div class="card-body">
        <h3><%= flat.name %></h3>
        <p><%= flat.address %></p>
        <i class="fas fa-users"></i>
        <%=  flat.number_of_guests %>
        <i class="fas fa-euro-sign" style="margin-left: 15px;"></i>
        <%= flat.price_per_night %>
        <div class="flex">
          <div class="flat-card-actions">
            <%= link_to "More info",  flat_path(flat), class: "text-primary" %>
            <%= link_to "Edit",  flat_path(flat), class: "text-warning" %>
            <%= link_to "Remove",  flat_path(flat), class: "text-danger" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="pic-container"></div>

<div class="container mt-n5">
  <div class="row">
    <div class="col-8">
      <div class="card p-3 rounded">
        <h1><%= @flat.name %></h1>
        <p class="flat-show-address"><%= @flat.address %></p>
      </div>
      <div class="card p-3 mt-3 h-100 rounded">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
      </div>
    </div>

    <div class="col-4">
      <div class="card p-3 rounded">
        <h5>Book this place!</h5>

        <form action="">
          <div class="form-inline">
            <div class="form-group">
              <label for="from">From:</label>
              <input type="text" class="form-control" id="from" placeholder="04/06/2019">
            </div>
          </div>
          <div class="form-inline">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="card p-3 rounded mt-3">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <i class="fas fa-users"></i>
            <%=  @flat.number_of_guests %>
            <i class="fas fa-euro-sign" style="margin-left: 15px;"></i>
            <%= @flat.price_per_night %>

          </div>
        </div>
      </div>
      <div class="card p-3 rounded mt-3">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fab fa-facebook-square fa-2x mr-2"></i>
            <i class="fab fa-twitter-square fa-2x mr-2"></i>
            <i class="fab fa-pinterest-square fa-2x mr-2"></i>
            <i class="fas fa-envelope fa-2x mr-2"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <h3>Simple Airbnb</h3>
      <%= link_to "Add flat", new_flat_path, class: "btn btn-outline-primary"%>
    </div>
    <%= yield %>
  </body>
</html>